### ISSUE TITLE
last bit of code

### ISSUE THREAD

**Issue by sguthals** [sguthals/Introduction-to-Data-Science#8]
airport_names = pd.Series(['ATL', 'DTW', 'JFK', 'MSP', 'SEA'])
delay_count_dataframe = pd.DataFrame(airport_names)
delay_count_dataframe[1] = delay_counts_per_airport
delay_count_dataframe.columns = ['ORIGIN', 'Delay Counts']
delay_count_dataframe.set_index('ORIGIN')

**Comment by Jaygup** [comment]
it works
thank you
